export const qk = {
  me: ["me"] as const,
  plan: ["plan", "me"] as const,
  plansCatalog: ["plans", "catalog"] as const,
  payments: (status?: string) => ["payments", status ?? "all"] as const,
  referralPayouts: (status?: string) =>
    ["referrals", "payouts", status ?? "all"] as const,
  users: ["users"] as const,
  user: (id: string) => ["user", id] as const,
  exams: (q?: object) => ["exams", q ?? {}] as const,
  exam: (id: string) => ["exam", id] as const,
  leaderboard: (id: string) => ["leaderboard", id] as const,
  attemptQuestions: (id: string) => ["attempt", id, "questions"] as const,
  report: (attemptId: string) => ["report", attemptId] as const,
  categories: ["practice", "categories"] as const,
  topics: (categoryId: string) => ["practice", "topics", categoryId] as const,
  topicsByGrouping: (grouping?: string) =>
    ["practice", "topics-by-grouping", grouping ?? "all"] as const,
  topicStats: (topicId: string) => ["practice", "topic-stats", topicId] as const,
  sets: (topicId: string) => ["practice", "sets", topicId] as const,
  set: (setId: string) => ["practice", "set", setId] as const,
  savedQuestions: ["practice", "saved-questions"] as const,
  setQuestions: (setId: string) => ["practice", "set-questions", setId] as const,
  questionReports: (status?: string) =>
    ["practice", "question-reports", status ?? "all"] as const,
  courses: ["courses"] as const,
  course: (id: string) => ["course", id] as const,
  material: (id: string) => ["material", id] as const,
  tutor: (id: string) => ["tutor", id] as const,
  notes: ["notes"] as const,
  analyticsDashboard: ["analytics", "dashboard"] as const,
  analyticsOverview: ["analytics", "overview"] as const,
  adminMarketingAnalytics: ["admin", "analytics", "marketing"] as const,
  streak: ["streak", "me"] as const,
  weekly: ["streak", "weekly"] as const,
  profile: ["profile", "me"] as const,
  settings: ["profile", "settings"] as const,
};
