export type CutoffEntry = {
  program: string;
  point: number;
};

export const selfSponsoredCutoffs: CutoffEntry[] = [
  { program: "Bachelor of Arts in Accounting and Finance (CoBE)", point: 65 },
  { program: "Bachelor of Arts in Broadcast and Multimedia Journalism", point: 59 },
  { program: "Bachelor of Arts in Business Administration and Information Systems", point: 76 },
  { program: "Bachelor of Arts in Economics (CoBE)", point: 69 },
  { program: "Bachelor of Arts in Logistics and Supply Chain Management", point: 69 },
  { program: "Bachelor of Arts in Management", point: 67 },
  { program: "Bachelor of Arts in Marketing Management", point: 70 },
  { program: "Bachelor of Arts in Music", point: 56 },
  { program: "Bachelor of Arts in Political Science and International Relations", point: 69 },
  { program: "Bachelor of Arts in Psychology", point: 70 },
  { program: "Bachelor of Arts in Public Administration and Development Management", point: 56 },
  { program: "Bachelor of Arts in Public Relations and Strategic Communication", point: 56 },
  { program: "Bachelor of Arts in Sociology and Social Anthropology", point: 56 },
  { program: "Bachelor of Fine Arts", point: 55 },
  { program: "Bachelor of Laws (LL.B.)", point: 73 },
  { program: "Bachelor of Pharmacy", point: 72 },
  { program: "Bachelor of Science in Chemical Engineering", point: 55 },
  { program: "Bachelor of Science in Anesthesia", point: 58 },
  { program: "Bachelor of Science in Architecture", point: 73 },
  { program: "Bachelor of Science in Biology", point: 58 },
  { program: "Bachelor of Science in Biomedical Engineering", point: 65 },
  { program: "Bachelor of Science in Chemistry", point: 63 },
  { program: "Bachelor of Science in Civil Engineering", point: 53 },
  { program: "Bachelor of Science in Computer Science", point: 77 },
  { program: "Bachelor of Science in Construction Technology and Management", point: 52 },
  { program: "Bachelor of Science in Electrical and Computer Engineering", point: 70 },
  { program: "Bachelor of Science in Information Systems", point: 74 },
  { program: "Bachelor of Science in Mechanical Engineering", point: 62 },
  { program: "Bachelor of Science in Medical Laboratory Sciences", point: 61 },
  { program: "Bachelor of Science in Medical Radiologic Technology", point: 52 },
  { program: "Bachelor of Science in Physics", point: 55 },
  { program: "Bachelor of Science in Software Engineering and Computing Technology", point: 79 },
  { program: "Bachelor of Science in Urban Planning and Design", point: 56 },
  { program: "Bachelor of Science in Comprehensive Nursing (Child Health Nursing)", point: 55 },
  { program: "Bachelor of Social Work", point: 56 },
  { program: "Doctor of Dental Medicine (DMD)", point: 78 },
  { program: "Doctor of Medicine", point: 79 },
  { program: "Natural Science Freshman Program - Self Sponsored", point: 72 },
  { program: "Social Science Freshman Program - Self Sponsored", point: 63 },
];

export const governmentSponsoredCutoffs: CutoffEntry[] = [
  { program: "Natural Science Freshman Program - Female", point: 78 },
  { program: "Natural Science Freshman Program - General", point: 83 },
  { program: "Social Science Freshman Program - Female", point: 57 },
  { program: "Social Science Freshman Program - General", point: 63 },
];

export const selfSponsoredCutoffs2024: CutoffEntry[] = [
  { program: "Bachelor of Pharmacy", point: 68 },
  { program: "Bachelor in Social Work", point: 54 },
  { program: "Bachelor of Arts in Logistics and Supply Chain Management", point: 56 },
  { program: "Bachelor of Arts in Accounting and Finance", point: 56 },
  { program: "Bachelor of Arts in Broadcast and Multimedia Journalism", point: 56 },
  { program: "Bachelor of Arts in Business Administration and Information Systems", point: 69 },
  { program: "Bachelor of Arts in Economics", point: 61 },
  { program: "Bachelor of Arts in Management", point: 56 },
  { program: "Bachelor of Arts in Marketing Management", point: 65 },
  { program: "Bachelor of Arts in Political Science and International Relations", point: 61 },
  { program: "Bachelor of Arts in Psychology", point: 60 },
  { program: "Bachelor of Arts in Public Administration and Development Management", point: 54 },
  { program: "Bachelor of Arts in Public Relations and Strategic Communication", point: 54 },
  { program: "Bachelor of Arts in Sociology and Social Anthropology", point: 54 },
  { program: "Bachelor of Fine Arts", point: 54 },
  { program: "Bachelor of Laws (LL.B.)", point: 70 },
  { program: "Bachelor of Science in Chemical Engineering", point: 63 },
  { program: "Bachelor of Science in Anesthesia", point: 63 },
  { program: "Bachelor of Science in Architecture", point: 63 },
  { program: "Bachelor of Science in Biomedical Engineering", point: 63 },
  { program: "Bachelor of Science in Civil Engineering", point: 63 },
  { program: "Bachelor of Science in Computer Science", point: 77 },
  { program: "Bachelor of Science in Electrical and Computer Engineering", point: 63 },
  { program: "Bachelor of Science in Information Systems", point: 63 },
  { program: "Bachelor of Science in Mechanical Engineering", point: 63 },
  { program: "Bachelor of Science in Medical Laboratory Sciences", point: 63 },
  { program: "Bachelor of Science in Medical Radiologic Technology", point: 65 },
  { program: "Bachelor of Science in Physics", point: 63 },
  { program: "Bachelor of Science in Software Engineering and Computing Technology", point: 78 },
  { program: "Bachelor of Science in Comprehensive Nursing", point: 63 },
  { program: "Doctor of Dental Medicine (DMD)", point: 75 },
  { program: "Doctor of Medicine", point: 79 },
];

export const governmentSponsoredCutoffs2024: CutoffEntry[] = [
  { program: "Natural Sciences", point: 64 },
  { program: "Social Sciences", point: 51 },
];
